on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Node CI"]
    types:
      - completed

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install --no-package-lock
      - run: npm run lint
      - run: npm test
      - run: npm publish
